# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20171206_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_rank_1',
            old_name='movieCode',
            new_name='moviecode',
        ),
        migrations.RenameField(
            model_name='movie_rank_2',
            old_name='movieCode',
            new_name='moviecode',
        ),
        migrations.RenameField(
            model_name='movie_rank_3',
            old_name='movieCode',
            new_name='moviecode',
        ),
        migrations.RenameField(
            model_name='movie_rank_4',
            old_name='movieCode',
            new_name='moviecode',
        ),
        migrations.RenameField(
            model_name='movie_rank_5',
            old_name='movieCode',
            new_name='moviecode',
        ),
        migrations.RenameField(
            model_name='movie_rank_6',
            old_name='movieCode',
            new_name='moviecode',
        ),
    ]
