# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmovie',
            old_name='movieCode',
            new_name='moviecode',
        ),
    ]
