# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieCode', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.URLField()),
                ('accessUrl', models.URLField()),
                ('accessImg', models.CharField(max_length=50)),
                ('releaseDate', models.DateField()),
                ('rate', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('scoreAct', models.IntegerField()),
                ('scoreStory', models.IntegerField()),
                ('scoreDirector', models.IntegerField()),
                ('scoreOST', models.IntegerField()),
                ('scoreVisual', models.IntegerField()),
                ('scoreFresh', models.IntegerField()),
            ],
        ),
    ]
