# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_remove_movie_accessurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rate',
            new_name='audits',
        ),
        migrations.AddField(
            model_name='movie',
            name='showtime',
            field=models.IntegerField(default=0),
        ),
    ]
