# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20171205_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('peopleCd', models.IntegerField(primary_key=True, serialize=False)),
                ('peopleNm', models.CharField(max_length=200)),
                ('peopleNmEn', models.CharField(max_length=200)),
                ('sex', models.BooleanField()),
                ('repRoleNm', models.CharField(max_length=200)),
                ('filmos', models.ManyToManyField(related_name='filmos', to='detail.Movie')),
            ],
        ),
    ]
