# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
