# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0006_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='showtime',
            new_name='opendate',
        ),
    ]
