# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0008_auto_20171206_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releaseDate',
            new_name='opendate',
        ),
    ]
