# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0009_auto_20171206_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scoreAct',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scoreDirector',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scoreFresh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scoreOST',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scoreStory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scoreVisual',
            field=models.FloatField(),
        ),
    ]
