# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0011_auto_20171206_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
