# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0012_movie_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='titleEn',
            field=models.CharField(default='', max_length=200),
        ),
    ]
