# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0014_auto_20171215_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieCode',
            new_name='moviecode',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='scoreAct',
            new_name='scoreact',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='scoreDirector',
            new_name='scoredirector',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='scoreFresh',
            new_name='scorefresh',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='scoreOST',
            new_name='scoreost',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='scoreStory',
            new_name='scorestory',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='scoreVisual',
            new_name='scorevisual',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='titleEn',
            new_name='titleen',
        ),
    ]
