# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0017_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='moviecode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
