# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0018_auto_20171215_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='openyear',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
