# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0019_movie_openyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nation', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OpenYear',
            fields=[
                ('openyear', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
