# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0020_genre_nation_openyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='openyear',
        ),
    ]
