# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0021_auto_20171217_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.Nation'),
        ),
        migrations.AddField(
            model_name='movie',
            name='openyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.OpenYear'),
        ),
    ]
