# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0022_auto_20171217_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='repRoleNm',
        ),
        migrations.AlterField(
            model_name='people',
            name='peopleNmEn',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
