# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0023_auto_20171219_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='filmos',
            new_name='moviecode',
        ),
    ]
