# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0024_auto_20171219_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scoreact',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scoredirector',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scorefresh',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scoreost',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scorestory',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scorevisual',
        ),
    ]
