# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0025_auto_20171219_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreact',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scoredirector',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scorefresh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scorestory',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scorevisual',
            field=models.FloatField(null=True),
        ),
    ]
